@host = https://localhost
@port = 7157
@Restaurants.api_HostAddress = {{host}}:{{port}}  
@token =CfDJ8EKpNWjzxx5NkmgcT6qQodRX8GyJpmxL4VIXFkOYHjySHNMotDmfMrGmLnYCmeVyDQHOlA_lxLVeBVpKj77676oksJJJr2Xe1brRXCKnPh5dNPSuW3rIa3zezw1rG-2-vIwUbd6iXG3SH7BPXi3ceOdaxNcLfal0qUM6aqPD7MkVOz6cmJBV2cb-sdtMhS7l1Roq3dkmh2jrwc5fAJ4nMw5cs-Illh1F-9yygEhFjkWh-lheUxrJkT0PE8s_4l1ZfYfE-0ePBdOaJusVK5dees9YJYEkoyX2tjna0xOoBFaTh771aXH6elbnSEOXC4EH0sMbGZy9V8-hENLT1z74X349nLfj9Y8u-fjrioczp4pyROJVNmNp3p-eSH4tMoudagqvjNxYdZejApYsTZYrZPwVN6UCgJR8TG1j3X7E9T198r2hEPZb1WuvbGS-56RB0xiBxQf3c19uzHslL1hfS3-E7X2Yp5iISAepTHJPi0S6HYddbk3IBfTXsS2SCrmX_Xb3z4gB35MzeAnlHWGZ3e9XHXn5_8sVYYmNkydI2LDKZxJ9IPLElEATUNzw9fjsQ8XQcy8yH__aEXpTeQRXnDyzUf6rVle-1yG86pXJDHTz1-CCVvjFWtfC3ccKYtQTxviOVzuvasRyVlHhf0PDqjIAbjc7Wu8uLer55BNrhELH0TMXA1oMz7tD3zYBAIKn5ELyt12HshGYr6QZjhCu4Mxhpe3ysstls4D7OEXxhyXLgWrASuhLE58EWYMGv6t-MGTq4Q7JJCuNRtTxl1bTYXQlRmz36t83MlS_w_wWA-gy
###
//Get all restaurants
GET {{Restaurants.api_HostAddress}}/api/restaurants
#Authorization: Bearer {{token}}


###
//Get single restaurant
GET {{Restaurants.api_HostAddress}}/api/restaurants/16
Accept: application/json
#Authorization: Bearer {{token}}


###
//Add restaurant
POST {{Restaurants.api_HostAddress}}/api/restaurants
Content-type: application/json
Authorization: Bearer {{token}}

{
  "Name": "SuSS",
  "Description": "Expensiev Coffee shop",
  "Category": "Italian",
  "ContactEmail":"suzz@gmail.com",
  "ContactNumber":"090909090",
  "City": "Alexandria",
  "Street": "kafr abdo",
  "PostalCode": 3123
}

###
//Get single restaurant
GET https://localhost:7157/api/restaurants/35

###
//delete restaurant
DELETE {{Restaurants.api_HostAddress}}/api/restaurants/35

###
//update restaurant
PATCH {{Restaurants.api_HostAddress}}/api/restaurants/35
Content-Type: application/json

{
  "Name":"Carbs",
  "Description":"Italian"
}

###
//Dishes

//add dish to specific restaurant
POST {{Restaurants.api_HostAddress}}/api/restaurants/3/dishes
Content-Type : application/json

{
  "Name": "Apple",
  "Description":"Fresh" ,
  "Price":"10" ,
  "KiloCalories": 200
}


###
//get all dishes for a specific restaurant
GET {{Restaurants.api_HostAddress}}/api/restaurants/1/dishes


###
//get a specific dish for a specific restaurant
GET {{Restaurants.api_HostAddress}}/api/restaurants/1/dishes/2

###
//delete dishes of a restaurant
DELETE {{Restaurants.api_HostAddress}}/api/restaurants/100/dishes

###
//register new user
POST {{Restaurants.api_HostAddress}}/api/identity/register
Content-Type : application/json
{
  "email" : "owner@gmail.com",
  "password" : "Password1!"
}

###
//login existing user
POST {{Restaurants.api_HostAddress}}/api/identity/login
Content-Type : application/json
{
  "email" : "admin@gmail.com",
  "password" : "Password1!"
}

###
//edit user info
PATCH {{Restaurants.api_HostAddress}}/api/identity/user
Content-Type : application/json
Authorization : Bearer {{token}}
{
  "dateOfBirth" : "2002-08-24",
  "Nationality" : "Egyptian"
}
###
//assign user to role
POST {{Restaurants.api_HostAddress}}/api/identity/userRole
Content-Type : application/json
Authorization : Bearer {{token}}
{
  "userEmail" : "mayayounes02@gmail.com",
  "roleName" : "user"
}
###
//unassign user to role
DELETE {{Restaurants.api_HostAddress}}/api/identity/userRole
Content-Type : application/json
Authorization : Bearer {{token}}
{
  "userEmail" : "mayayounes02@gmail.com",
  "roleName" : "user"
}