@host = https://localhost
@port = 7157
@Restaurants.api_HostAddress = {{host}}:{{port}}  
@token =CfDJ8EKpNWjzxx5NkmgcT6qQodR9qIY5JOxu7AFAaXs3VUsLUpyVtznA9YnkeexfPBPRlm4-SoIwA9u_QyL5kwn19XF0VCY4bxkua7nkPcRtWTqYE5yWFjypNIE67T1NguWF_Km6fCruD097s-fnvMT4pfv0AQw93r6LrGJs6rAZlOfC7x6qbFn4jEvB6m4vOMxCa-9K0rJydrMkDt9yu21dITF5RvQm3esUqugy9Wnmrv_0o11bpaf8PGYVuxvAbj4NrcusDOyXKDW66eEqVoGxwDYUxsIce-cg7soKEDBLxSmkvOGDI_6_2f9G2m07N1uCihvM2LHUVwjw6LuAuSLPh8CyPzxWDGGXNsVBJiS8J1J0ri4X_Hp3weooU_F906DWwYgaT8552GkLvlD9oG4x6eLknE0ohlO_FBurOlpFrk6H-aRDoxur1r4ct60OIxp51bS6XhUPYwlsz7TIKFt-K62ubccKF-RmiXAiF1XfJHfeLAzmf1ya8Hsml5GTmOcLtR216Zbr9NzIziptQsI27rPbTVaPKVop0ZF6oWMWLK_R_0zrGdCIKXPdLWOzxT-6w5pb0Ro9m1SG5WAfCTAzk2xqteN7MPcp-O0A7dYLRxVyRJnmkrWYLe6H05oCeoaZWvwbQwm6fzYos4nPPejjHRPa8neZIe8UYA1M1GUWmVnFt9VrsN6OpilCo2BWkbxbReMJllxXfMjidtzOK0P0WhIx8Bh0lzJs1NicjjiIL_mRmfIcWiIby2fwRy33dyTah7zrQfOCJKdH-xuMLt0T7Htg1PWLQ3QKAjqx-5SwaWly
###
//Get all restaurants
GET {{Restaurants.api_HostAddress}}/api/restaurants
Accept: application/json
Authorization: Bearer {{token}}

###
//Get all restaurants by searchPhrase (Pagination)
GET {{Restaurants.api_HostAddress}}/api/restaurants?searchPhrase=&pageSize=30&pageNumber=2&sortBy=city
Accept: application/json
Authorization: Bearer {{token}}


###
//Get single restaurant
GET {{Restaurants.api_HostAddress}}/api/restaurants/16
Accept: application/json
Authorization: Bearer {{token}}


###
//Add restaurant
POST {{Restaurants.api_HostAddress}}/api/restaurants
Content-type: application/json
Authorization: Bearer {{token}}

{
  "Name": "The Walk",
  "Description": "byBeach",
  "Category": "Italian",
  "ContactEmail":"point6@gmail.com",
  "ContactNumber":"33",
  "City": "Alexandria",
  "Street": "Sedy gaber",
  "PostalCode": 889
}

###
//Get single restaurant
GET https://localhost:7157/api/restaurants/37
Authorization: Bearer {{token}}


###
//delete restaurant
DELETE {{Restaurants.api_HostAddress}}/api/restaurants/37
Authorization: Bearer {{token}}

###
//update restaurant
PATCH {{Restaurants.api_HostAddress}}/api/restaurants/37
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name":"Metro",
  "Description":"Italian"
}

###
//Dishes

//add dish to specific restaurant
POST {{Restaurants.api_HostAddress}}/api/restaurants/3/dishes
Content-Type : application/json

{
  "Name": "Apple",
  "Description":"Fresh" ,
  "Price":"10" ,
  "KiloCalories": 200
}


###
//get all dishes for a specific restaurant
GET {{Restaurants.api_HostAddress}}/api/restaurants/1/dishes
Authorization: Bearer {{token}}


###
//get a specific dish for a specific restaurant
GET {{Restaurants.api_HostAddress}}/api/restaurants/1/dishes/2

###
//delete dishes of a restaurant
DELETE {{Restaurants.api_HostAddress}}/api/restaurants/100/dishes

###
//register new user
POST {{Restaurants.api_HostAddress}}/api/identity/register
Content-Type : application/json
{
  "email" : "Owner2@gmail.com",
  "password" : "Password1!"
}

###
//login existing user
POST {{Restaurants.api_HostAddress}}/api/identity/login
Content-Type : application/json
{
  "email" : "mayayounes02@gmail.com",
  "password" : "Password1!"
}

###
//edit user info
PATCH {{Restaurants.api_HostAddress}}/api/identity/user
Content-Type : application/json
Authorization : Bearer {{token}}
{
  "dateOfBirth" : "2002-08-24",
  "Nationality" : "Egyptian"
}
###
//assign user to role
POST {{Restaurants.api_HostAddress}}/api/identity/userRole
Content-Type : application/json
Authorization : Bearer {{token}}
{
  "userEmail" : "Owner2@gmail.com",
  "roleName" : "Owner"
}
###
//unassign user to role
DELETE {{Restaurants.api_HostAddress}}/api/identity/userRole
Content-Type : application/json
Authorization : Bearer {{token}}
{
  "userEmail" : "mayayounes02@gmail.com",
  "roleName" : "user"
}
###
//patch user
PATCH {{Restaurants.api_HostAddress}}/api/identity/user
Content-Type : application/json
Authorization : Bearer {{token}}
{
  "DateOfBirth" : "2009-07-01",
  "Nationality" : "French"
}